### ISSUE TITLE
Question about the function "fold"

### ISSUE THREAD

**Issue by datduong** [fann1993814/LabeledLDA#2]
Hi, in the description you say that 
> The function "fold" to make new document acquire P(z|new_d).

What does this function "fold" exactly do? For example, I see that "fold" takes in a new document. Does "fold" predict the labels for new documents? Why does "fold" also contain an argument "iteration" if it does only prediction? 

Thank you.

**Comment by fann1993814** [comment]
To predict the topic distribution of unseen documents P(z|new_d), it also apply the gibbs sampling by multiple iterations. It also like as PLSA, or LDA.

**Comment by fann1993814** [comment]
> Hi, in the description you say that
> 
> > The function "fold" to make new document acquire P(z|new_d).
> 
> What does this function "fold" exactly do? For example, I see that "fold" takes in a new document. Does "fold" predict the labels for new documents? Why does "fold" also contain an argument "iteration" if it does only prediction?
> 
> Thank you.

To predict the topic distribution of unseen documents P(z|new_d), it also apply the gibbs sampling by multiple iterations. It also like as PLSA, or LDA. The fold function are similar the theta function. The theta function is aim to the known documents from the training corpus. However the fold function is for unseen documents.

**Comment by datduong** [comment]
Thank you for the clarification, and thanks for this code.

**Comment by davidkko** [comment]
It looks like it keeps the previous V from the training set. Does it do anything to keep information from the original word-topic distribution? Or is it creating a new one based on just the word inputs from the original document?

**Comment by datduong** [comment]
I see that it keeps the self.n_z_t and self.n_z.

**Comment by colinwxl** [comment]
Hi.
If my dataset is in a format of "one label for one doc", is suitable to use labeled LDA?

**Comment by fann1993814** [comment]
> Hi.
> If my dataset is in a format of "one label for one doc", is suitable to use labeled LDA?

Hi, colinwxl 
Labeled LDA usually is used for multiple label (also include one label). I don't know what your target? Do you want to obtain document representation (P(z|d)) or the relation between label and words (P(w|z))? If you want to obtain the latter one, I suggest you can try my another research HWE, https://github.com/fann1993814/hwe

**Comment by colinwxl** [comment]
> > Hi.
> > If my dataset is in a format of "one label for one doc", is suitable to use labeled LDA?
> 
> Hi, colinwxl
> Labeled LDA usually is used for multiple label (also include one label). I don't know what your target? Do you want to obtain document representation (P(z|d)) or the relation between label and words (P(w|z))? If you want to obtain the latter one, I suggest you can try my another research HWE, https://github.com/fann1993814/hwe

Thx for your reply. Actually, I care about both results. My documents consist of position-unrelated words, so what I need is a method ignoring words' positions. I will study your recommended HWE.
Thank you again.
